
api: 
  
  artifactId: "sys-claims-app-v1-dev"
  version: "1.0.0"
  majorVersion: "v1"
  port: "8082"
  
# reconnection configuration
"retries":
  "frequency": "1000"
  "attempts": "3"
  "timeout": "400000" 
  
tls.keystore:
 
 type: "pkcs12"
 alias: "server"
 path: "certs/sys-claims-cms-dev.p12"

jks.keystore:
 password: "mulesoft"
 type: "jks"
 path: "certs/keystore.jks" 
  
"autodiscovery":
  "id": "17510995"